set_property PACKAGE_PIN T4 [get_ports uart_txd]
set_property PACKAGE_PIN N5 [get_ports uart_rxd]
set_property PACKAGE_PIN P17 [get_ports sys_clk]
set_property PACKAGE_PIN P15 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
